sources:
  - name: Løgmansskrivstovan
    url: https://www.lms.fo/fo/kunning/tidindi/
  - name: Almanna- og bústaðamálaráðið
    url: https://www.abmr.fo/fo/kunning/tidindi/
  - name: Barna- og útbúgvingarmálaráðið
    url: https://www.bumr.fo/fo/kunning/tidindi/
  - name: Fiskivinnu- og samferðslumálaráðið
    url: https://www.fisk.fo/fo/kunning/tidindi/
  - name: Fíggjarmálaráðið
    url: https://www.fmr.fo/fo/kunning/tidindi/
  - name: Heilsu- og innlendismálaráðið
    url: https://www.hmr.fo/fo/kunning/tidindi/
  - name: Løgmálaráðið
    url: https://www.logir.fo/fo/kunning/tidindi/
  - name: Mentamálaráðið
    url: https://www.mmr.fo/fo/kunning/tidindi/
  - name: Uttanríkis- og vinnumálaráðið
    url: https://www.uvmr.fo/fo/kunning/tidindi/
  - name: Hoyringarportalurin
    url: https://www.foroyalandsstyri.fo/fo/kunning/uppskot-til-ummaelis/
